In [1]:
import numpy as np
import time

In [3]:
#test speed
def sum_trad():
    start = time.time()
    X = range(10000000)
    Y = range(10000000)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - start
    
def sum_numpy():
    start = time.time()
    X = np.arange(10000000) 
    Y = np.arange(10000000) 
    Z=X+Y
    return time.time() - start

print 'time sum:',sum_trad(),'  time sum numpy:',sum_numpy()

 time sum: 2.1142539978   time sum numpy: 0.0807049274445


In [7]:
#array creation
arr = np.array([2, 6, 5, 9], float)
print arr
print type(arr)

[ 2.  6.  5.  9.]
<type 'numpy.ndarray'>


In [5]:
arr = np.array([1, 2, 3], float)
print arr.tolist()
print list(arr)

[1.0, 2.0, 3.0]

In [6]:
arr = np.array([1, 2, 3], float)
arr1 = arr
arr2 = arr.copy()
arr[0] = 0
print arr
print arr1
print arr2

array([ 1.,  2.,  3.])

In [9]:
arr = np.array([10, 20, 33], float)
print arr
arr.fill(1)
print arr

[ 10.  20.  33.]
[ 1.  1.  1.]


In [10]:
print np.random.permutation(3)
print np.random.normal(0,1,5)
print np.random.random(5)

[1 2 0]
[ 0.26679111  0.38501227  2.38316066  0.02675034 -0.43446008]
[ 0.80753324  0.55991096  0.48118454  0.2833164   0.03833485]


In [11]:
print np.identity(5, dtype=float)
print np.eye(3, k=1, dtype=float)

print np.ones((2,3), dtype=float)
print np.zeros(6, dtype=int)
arr = np.array([[13, 32, 31], [64, 25, 76]], float)
print np.zeros_like(arr)
print np.ones_like(arr)
arr1 = np.array([1,3,2])
arr2 = np.array([3,4,6])
print np.vstack([arr1,arr2])
print np.random.rand(2,3)
print np.random.multivariate_normal([10, 0], [[3, 1], [1, 4]], size=[5,])

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[0 0 0 0 0 0]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[1 3 2]
 [3 4 6]]
[[ 0.60363091  0.30308355  0.61109112]
 [ 0.63595304  0.38100017  0.00487817]]
[[  9.87749252  -0.38663954]
 [ 10.94265725  -0.91410028]
 [ 10.22591511   1.61752964]
 [  9.00656673   2.16278221]
 [  9.16733481  -3.7865277 ]]


In [12]:
#array manipulations
arr = np.array([2., 6., 5., 5.])
print arr[:3]
print arr[3]
arr[0] = 5.
print arr

[ 2.  6.  5.]
5.0
[ 5.  6.  5.  5.]


In [14]:
print np.unique(arr)
print np.sort(arr)
print np.argsort(arr)
np.random.shuffle(arr)
print arr
print np.array_equal(arr,np.array([1,3,2]))

[ 5.  6.]
[ 5.  5.  5.  6.]
[0 1 3 2]
[ 6.  5.  5.  5.]
False


In [16]:
matrix = np.array([[ 4., 5., 6.], [2, 3, 6]], float)
print matrix
print matrix[0,0],'--',matrix[0,2]
arr = np.array([[ 4., 5., 6.], [ 2., 3., 6.]], float)
print arr[1:2,2:3]
print arr[1,:]
print arr[:,2]
print arr[-1:,-2:]
arr = np.array([[10, 29, 23], [24, 25, 46]], float)
print arr
print arr.flatten()
print arr.shape
print arr.dtype
int_arr = matrix.astype(np.int32)
print int_arr

[[ 4.  5.  6.]
 [ 2.  3.  6.]]
4.0 -- 6.0
[[ 6.]]
[ 2.  3.  6.]
[ 6.  6.]
[[ 3.  6.]]
[[ 10.  29.  23.]
 [ 24.  25.  46.]]
[ 10.  29.  23.  24.  25.  46.]
(2, 3)
float64
[[4 5 6]
 [2 3 6]]


In [17]:
arr = np.array([[ 4., 5., 6.], [ 2., 3., 6.]], float)
print len(arr)
arr = np.array([[ 4., 5., 6.], [ 2., 3., 6.]], float)
print 2 in arr
print 0 in arr

2
True
False


In [18]:
arr = np.array(range(8), float)
print arr
arr = arr.reshape((4,2))
print arr
print arr.shape

[ 0.  1.  2.  3.  4.  5.  6.  7.]
[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]]
(4, 2)


In [20]:
arr = np.array(range(6), float).reshape((2, 3))
print arr
print arr.transpose()

[[ 0.  1.  2.]
 [ 3.  4.  5.]]
[[ 0.  3.]
 [ 1.  4.]
 [ 2.  5.]]


In [21]:
matrix = np.arange(15).reshape((3, 5))
print matrix
print matrix.T

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [22]:
arr = np.array([14, 32, 13], float)
print arr
print arr[:,np.newaxis]
print arr[:,np.newaxis].shape
print arr[np.newaxis,:]
print arr[np.newaxis,:].shape

[ 14.  32.  13.]
[[ 14.]
 [ 32.]
 [ 13.]]
(3, 1)
[[ 14.  32.  13.]]
(1, 3)


In [24]:
arr1 = np.array([10,22], float)
arr2 = np.array([31,43,54,61], float)
arr3 = np.array([71,82,29], float)
print np.concatenate((arr1, arr2, arr3))
arr1 = np.array([[11, 12], [32, 42]], float)
arr2 = np.array([[54, 26], [27,28]], float)
print np.concatenate((arr1,arr2))
print np.concatenate((arr1,arr2), axis=0)
print np.concatenate((arr1,arr2), axis=1)

[ 10.  22.  31.  43.  54.  61.  71.  82.  29.]
[[ 11.  12.]
 [ 32.  42.]
 [ 54.  26.]
 [ 27.  28.]]
[[ 11.  12.]
 [ 32.  42.]
 [ 54.  26.]
 [ 27.  28.]]
[[ 11.  12.  54.  26.]
 [ 32.  42.  27.  28.]]


In [27]:
arr = np.array([10, 20, 30], float)
str = arr.tostring()
print str
print np.fromstring(str)

$@4@>@
[ 10.  20.  30.]


In [29]:
#array operations
arr1 = np.array([1,2,3], float)
arr2 = np.array([1,2,3], float)
print arr1+arr2
print arr1-arr2
print arr1 * arr2
print arr2 / arr1
print arr1 % arr2
print arr2**arr1

[ 2.  4.  6.]
[ 0.  0.  0.]
[ 1.  4.  9.]
[ 1.  1.  1.]
[ 0.  0.  0.]
[  1.   4.  27.]


In [30]:
arr1 = np.array([1,2,3], float)
arr2 = np.array([1,2], float)
print arr1 + arr2

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [32]:
arr1 = np.array([[1, 2], [3, 4], [5, 6]], float)
arr2 = np.array([1, 2], float)
print arr1
print arr2
print arr1 + arr2
arr1 = np.zeros((2,2), float)

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]
[ 1.  2.]
[[ 2.  4.]
 [ 4.  6.]
 [ 6.  8.]]


In [34]:
arr1 = np.zeros((2,2), float)
arr2 = np.array([1., 2.], float)
print arr1
print arr2
print arr1+arr2
print arr1 + arr2[np.newaxis,:]
print arr1 + arr2[:,np.newaxis]

[[ 0.  0.]
 [ 0.  0.]]
[ 1.  2.]
[[ 1.  2.]
 [ 1.  2.]]
[[ 1.  2.]
 [ 1.  2.]]
[[ 1.  1.]
 [ 2.  2.]]


In [35]:
arr = np.array([[1, 2], [5, 9]], float)
print arr >= 7
print arr[arr >= 7]
arr[np.logical_and(arr > 5, arr < 11)]
print arr

[[False False]
 [False  True]]
[ 9.]
[[ 1.  2.]
 [ 5.  9.]]


In [36]:
arr1 = np.array([1, 4, 5, 9], float)
arr2 = np.array([0, 1, 1, 3, 1, 1, 1], int)
print arr1[arr2]
arr = np.array([1, 4, 5, 9], float)
print arr[[0, 1, 1, 3, 1]]

[ 1.  4.  4.  9.  4.  4.  4.]
[ 1.  4.  4.  9.  4.]


In [37]:
arr1 = np.array([[1, 2], [5, 13]], float)
arr2 = np.array([1, 0, 0, 1], int)
arr3 = np.array([1, 1, 0, 1], int)
print arr1[arr2,arr3]
arr1 = np.array([7, 6, 6, 9], float)
arr2 = np.array([1, 0, 1, 3, 3, 1], int)
print arr1.take(arr2)
arr1 = np.array([[10, 21], [62, 33]], float)
arr2 = np.array([0, 0, 1], int)
print arr1.take(arr2, axis=0)
print arr1.take(arr2, axis=1)
arr1 = np.array([2, 1, 6, 2, 1, 9], float)
arr2 = np.array([3, 10, 2], float)
arr1.put([1, 4], arr2)
print arr1

[ 13.   2.   1.  13.]
[ 6.  7.  6.  9.  9.  6.]
[[ 10.  21.]
 [ 10.  21.]
 [ 62.  33.]]
[[ 10.  10.  21.]
 [ 62.  62.  33.]]
[  2.   3.   6.   2.  10.   9.]


In [38]:
arr1 = np.array([[11,22], [23,14]], float)
arr2 = np.array([[25,30], [13,33]], float)
print arr1*arr2

[[ 275.  660.]
 [ 299.  462.]]


In [39]:
#linear algebra operations
X = np.arange(15).reshape((3, 5))
print X
print X.T
print np.dot(X .T, X)#X^T X

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[125 140 155 170 185]
 [140 158 176 194 212]
 [155 176 197 218 239]
 [170 194 218 242 266]
 [185 212 239 266 293]]


In [40]:
arr1 = np.array([12, 43, 10], float)
arr2 = np.array([21, 42, 14], float)
print np.outer(arr1, arr2)
print np.inner(arr1, arr2)
print np.cross(arr1, arr2)

[[  252.   504.   168.]
 [  903.  1806.   602.]
 [  210.   420.   140.]]
2198.0
[ 182.   42. -399.]


In [41]:
matrix = np.array([[74, 22, 10], [92, 31, 17], [21, 22, 12]], float)
print matrix
print np.linalg.det(matrix)
inv_matrix = np.linalg.inv(matrix)
print inv_matrix
print np.dot(inv_matrix,matrix)
vals, vecs = np.linalg.eig(matrix)
print vals
print vecs

[[ 74.  22.  10.]
 [ 92.  31.  17.]
 [ 21.  22.  12.]]
-2852.0
[[ 0.00070126  0.01542777 -0.02244039]
 [ 0.26192146 -0.23772791  0.11851332]
 [-0.48141655  0.4088359  -0.09467041]]
[[  1.00000000e+00   0.00000000e+00  -5.55111512e-17]
 [  1.52655666e-16   1.00000000e+00  -2.22044605e-16]
 [  3.10862447e-15   8.88178420e-16   1.00000000e+00]]
[ 107.99587441   11.33411853   -2.32999294]
[[-0.57891525 -0.21517959  0.06319955]
 [-0.75804695  0.17632618 -0.58635713]
 [-0.30036971  0.96052424  0.80758352]]


In [ ]:
#Statistics and mathematical functions
arr = np.random.rand(8, 4)
print arr.mean()
print np.mean(arr)
print arr.sum()